services:
  db:
    image: pgvector/pgvector:pg17
    container_name: documind-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret1
      - POSTGRES_DB=documind_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
